//! The engine's constant tables, committed as TSV and read back here.
//!
//! The text is generated by [`generate`] from the vendored engine source
//! and committed under `native/tables/`. It is embedded rather than read
//! from disk, so a caller needs the binary and nothing else, and
//! `native/tests/tables.rs` fails if regenerating produces different
//! bytes.

pub mod generate;

/// A cell that is not the number the column is read as.
#[derive(Debug, thiserror::Error)]
pub enum TableError {
    #[error("{table}: no column named {column}")]
    NoColumn { table: &'static str, column: String },

    #[error("{table}: row {row} has {found} cells, not {want}")]
    RowWidth {
        table: &'static str,
        row: usize,
        want: usize,
        found: usize,
    },

    #[error("{table}.{column} row {row}: {cell:?} is not an integer")]
    NotAnInteger {
        table: &'static str,
        column: String,
        row: usize,
        cell: String,
    },

    #[error("no table named {name}")]
    NoTable { name: String },
}

/// One table's committed TSV.
pub struct Embedded {
    /// The file stem, and the ClickHouse table name.
    pub name: &'static str,
    /// The file's whole text: a header row of column names, then one row
    /// per entry.
    pub tsv: &'static str,
}

macro_rules! embedded {
    ($($name:literal),* $(,)?) => {
        [$(Embedded { name: $name, tsv: include_str!(concat!("../../tables/", $name, ".tsv")) }),*]
    };
}

/// Every table, in the order `generate` produces them.
pub const TABLES: [Embedded; 15] = embedded![
    "states",
    "action_functions",
    "mobjinfo",
    "sprnames",
    "weaponinfo",
    "animdefs",
    "switchlist",
    "checkcoord",
    "finetangent",
    "finesine",
    "tantoangle",
    "rndtable",
    "fuzzoffset",
    "gammatable",
    "messages",
];

/// One table's rows, split on tabs.
pub struct Rows {
    pub name: &'static str,
    pub columns: Vec<&'static str>,
    pub rows: Vec<Vec<&'static str>>,
}

impl Rows {
    /// The position of `column`.
    pub fn column(&self, column: &str) -> Result<usize, TableError> {
        self.columns
            .iter()
            .position(|c| *c == column)
            .ok_or_else(|| TableError::NoColumn {
                table: self.name,
                column: column.to_owned(),
            })
    }

    /// One column as integers, in row order.
    pub fn ints(&self, column: &str) -> Result<Vec<i64>, TableError> {
        let at = self.column(column)?;
        self.rows
            .iter()
            .enumerate()
            .map(|(row, cells)| {
                cells[at].parse().map_err(|_| TableError::NotAnInteger {
                    table: self.name,
                    column: column.to_owned(),
                    row,
                    cell: cells[at].to_owned(),
                })
            })
            .collect()
    }

    /// One column as text, in row order.
    pub fn texts(&self, column: &str) -> Result<Vec<&'static str>, TableError> {
        let at = self.column(column)?;
        Ok(self.rows.iter().map(|cells| cells[at]).collect())
    }
}

/// Reads a committed table by name.
///
/// Every row is checked to carry one cell per column, so a column read
/// never falls off the end of a short row.
pub fn table(name: &str) -> Result<Rows, TableError> {
    let embedded = TABLES
        .iter()
        .find(|t| t.name == name)
        .ok_or_else(|| TableError::NoTable {
            name: name.to_owned(),
        })?;
    let mut lines = embedded.tsv.lines();
    let columns: Vec<&str> = lines.next().unwrap_or_default().split('\t').collect();
    let mut rows = Vec::new();
    for (row, line) in lines.enumerate() {
        let cells: Vec<&str> = line.split('\t').collect();
        if cells.len() != columns.len() {
            return Err(TableError::RowWidth {
                table: embedded.name,
                row,
                want: columns.len(),
                found: cells.len(),
            });
        }
        rows.push(cells);
    }
    Ok(Rows {
        name: embedded.name,
        columns,
        rows,
    })
}

/// An insert of one table's committed TSV.
pub struct TableInsert {
    pub table: &'static str,
    /// The statement, which carries no data of its own.
    pub sql: String,
    /// The TSV to send as the statement's body.
    pub body: &'static str,
}

/// One insert per table, into `db`.
///
/// The rows travel as the request body in ClickHouse's own TSV format
/// rather than inside the statement text, so a 10,240-row table is one
/// short statement and one stream.
pub fn insert_statements(db: &str) -> Vec<TableInsert> {
    TABLES
        .iter()
        .map(|t| TableInsert {
            table: t.name,
            sql: format!("INSERT INTO {db}.{} FORMAT TSVWithNames", t.name),
            body: t.tsv,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_table_parses_with_one_cell_per_column() {
        for embedded in &TABLES {
            let rows = table(embedded.name).unwrap();
            assert!(!rows.rows.is_empty(), "{} is empty", embedded.name);
            // Every table but two is keyed by a dense index. `gammatable`
            // is keyed by the level first, and `messages` by the name the
            // engine defines the string under.
            assert_eq!(
                rows.columns[0],
                match embedded.name {
                    "gammatable" => "level",
                    "messages" => "name",
                    _ => "id",
                }
            );
        }
    }

    #[test]
    fn an_unknown_table_or_column_is_an_error() {
        assert!(matches!(table("nope"), Err(TableError::NoTable { .. })));
        assert!(matches!(
            table("rndtable").unwrap().ints("nope"),
            Err(TableError::NoColumn { .. })
        ));
    }

    #[test]
    fn inserts_name_the_database_and_stream_the_committed_text() {
        let inserts = insert_statements("clickdoom_native");
        assert_eq!(inserts.len(), TABLES.len());
        let states = &inserts[0];
        assert_eq!(
            states.sql,
            "INSERT INTO clickdoom_native.states FORMAT TSVWithNames"
        );
        assert!(states.body.starts_with("id\tsprite\tframe\t"));
    }
}
